__version__ = "0.0.1"

import frappe
import erpnext.accounts.doctype.pricing_rule.pricing_rule as pricing_rule_module
from advanced_pricing_rules.custom_pricing_rule import apply_pricing_rule_patch, get_pricing_rule_for_item_patch, apply_price_discount_rule_patch

pricing_rule_module.apply_pricing_rule = apply_pricing_rule_patch
pricing_rule_module.get_pricing_rule_for_item = get_pricing_rule_for_item_patch
pricing_rule_module.apply_price_discount_rule = apply_price_discount_rule_patch